apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-manifests
  namespace: aks-store
spec:
  project: default
  source:
    repoURL: https://github.com/kvPrabhanjan/abb-aks-demo.git
    targetRevision: HEAD
    path: argocd-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: aks-store 